/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-dim": "#d7dbda",
        "tertiary-fixed": "#ffe088",
        "tertiary-fixed-dim": "#e9c349",
        background: "#f6faf9",
        "secondary-fixed": "#d5e3ff",
        "on-error": "#ffffff",
        "inverse-primary": "#76d6d5",
        "inverse-on-surface": "#edf2f1",
        "on-tertiary-container": "#4f3e00",
        "surface-container-low": "#f0f4f3",
        "on-background": "#181c1c",
        "primary-container": "#008080",
        "surface-container-highest": "#dfe3e2",
        "on-tertiary-fixed": "#241a00",
        "surface-bright": "#f6faf9",
        "secondary-fixed-dim": "#a7c8ff",
        "primary-fixed-dim": "#76d6d5",
        tertiary: "#735c00",
        "on-primary-container": "#e3fffe",
        "on-secondary-fixed": "#001c3b",
        "surface-container-lowest": "#ffffff",
        outline: "#6e7979",
        "inverse-surface": "#2c3131",
        "on-secondary-fixed-variant": "#1e477b",
        "secondary-container": "#9ec2fe",
        "surface-variant": "#dfe3e2",
        "on-secondary": "#ffffff",
        primary: "#006565",
        "surface-tint": "#006a6a",
        "on-primary-fixed": "#002020",
        "on-primary-fixed-variant": "#004f4f",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e5e9e8",
        secondary: "#395f94",
        error: "#ba1a1a",
        "primary-fixed": "#93f2f2",
        "outline-variant": "#bdc9c8",
        "surface-container": "#ebefee",
        "error-container": "#ffdad6",
        "on-secondary-container": "#284f83",
        "tertiary-container": "#cca830",
        surface: "#f6faf9",
        "on-surface-variant": "#3e4949",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#574500",
        "on-surface": "#181c1c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-gap-lg": "24px",
        unit: "4px",
        "stack-gap-md": "16px",
        "stack-gap-sm": "8px",
        "container-padding": "20px",
        "section-margin": "40px",
      },
      fontFamily: {
        "data-label": ["PublicSans_600SemiBold"],
        "section-header": ["PublicSans_600SemiBold"],
        "body-main": ["PublicSans_400Regular"],
        "report-headline": ["PublicSans_700Bold"],
        "caption-caps": ["PublicSans_700Bold"],
      },
      fontSize: {
        "data-label": ["13px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "section-header": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-main": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "report-headline": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "caption-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
